job_titles:
  - job_title:
      extract:
        title: "Data Analyst"

      load:
        file: 
          load_target: "file"
          target_file_directory: "trading_price/data"
          target_file_name: "tesla.parquet"
        database:
          load_target: "database"
          target_table_name: "tesla_stock"

  - job_title: 
      extract:
        title: "Data Engineer"

      load:
        file: 
          load_target: "file"
          target_file_directory: "trading_price/data"
          target_file_name: "apple.parquet"
        database:
          load_target: "database"
          target_table_name: "apple_stock"
  
  - job_title: 
      extract:
        title: "Data Scientist"

      load:
        file: 
          load_target: "file"
          target_file_directory: "trading_price/data"
          target_file_name: "amazon.parquet"
        database:
          load_target: "database"
          target_table_name: "amazon_stock"
